packages:
  - projects/*
  - packages/**/*

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - prisma
  - unrs-resolver
