packages:
  - projects/*
  - packages/**/*

catalogs:
  prisma:
    prisma: 7.0.1
    "@prisma/client": "7.0.1"
    "@prisma/adapter-pg": "7.0.1"
    "@prisma/client-runtime-utils": "7.0.1"
  nest:
    "@nestjs/common": "11.0.1"
    "@nestjs/core": "11.0.1"
    "@nestjs/platform-express": "11.0.1"
    "@nestjs/config": "4.0.2"
    "@nestjs/jwt": "11.0.0"
  tailwind:
    tailwindcss: "4.1.18"
    "@tailwindcss/vite": "4.1.18"

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - prisma
  - unrs-resolver
