/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePublicRequestDto
 */
export interface CreatePublicRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'widgetId': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'email'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreatePublicRequestDto
     */
    'prizes'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'sectorId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePublicRequestDto
     */
    'isWin'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'device'?: CreatePublicRequestDtoDeviceEnum;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'referrer'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicRequestDto
     */
    'userAgent'?: string;
}

export const CreatePublicRequestDtoDeviceEnum = {
    desktop: 'desktop',
    mobile_ios: 'mobile_ios',
    mobile_android: 'mobile_android'
} as const;

export type CreatePublicRequestDtoDeviceEnum = typeof CreatePublicRequestDtoDeviceEnum[keyof typeof CreatePublicRequestDtoDeviceEnum];


