/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateWidgetDto
 */
export interface CreateWidgetDto {
    /**
     * The ID of the project this widget belongs to
     * @type {string}
     * @memberof CreateWidgetDto
     */
    'projectId': string;
    /**
     * The name of the widget
     * @type {string}
     * @memberof CreateWidgetDto
     */
    'name': string;
    /**
     * The type of the widget
     * @type {string}
     * @memberof CreateWidgetDto
     */
    'type': CreateWidgetDtoTypeEnum;
    /**
     * Whether the widget is enabled
     * @type {boolean}
     * @memberof CreateWidgetDto
     */
    'enabled': boolean;
    /**
     * JSON configuration for the widget
     * @type {object}
     * @memberof CreateWidgetDto
     */
    'config'?: object;
}

export const CreateWidgetDtoTypeEnum = {
    WHEEL: 'WHEEL',
    PIPELINE: 'PIPELINE',
    TIMER: 'TIMER',
    POSTCARD: 'POSTCARD'
} as const;

export type CreateWidgetDtoTypeEnum = typeof CreateWidgetDtoTypeEnum[keyof typeof CreateWidgetDtoTypeEnum];


