/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteProjectResponse
 */
export interface DeleteProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectResponse
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectResponse
     */
    'websiteUrl': string;
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteProjectResponse
     */
    'enabled': boolean;
}

