/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PublicWidget
 */
export interface PublicWidget {
    /**
     * Widget id
     * @type {string}
     * @memberof PublicWidget
     */
    'id': string;
    /**
     * Project id
     * @type {string}
     * @memberof PublicWidget
     */
    'projectId': string;
    /**
     * Widget type
     * @type {string}
     * @memberof PublicWidget
     */
    'type': PublicWidgetTypeEnum;
    /**
     * Whether widget is enabled
     * @type {boolean}
     * @memberof PublicWidget
     */
    'enabled': boolean;
    /**
     * Canonical widget configuration
     * @type {object}
     * @memberof PublicWidget
     */
    'config'?: object | null;
}

export const PublicWidgetTypeEnum = {
    WHEEL_OF_FORTUNE: 'WHEEL_OF_FORTUNE',
    CONVEYOR_OF_GIFTS: 'CONVEYOR_OF_GIFTS',
    ACTION_TIMER: 'ACTION_TIMER',
    POSTCARD: 'POSTCARD',
    CHEST_WITH_ACTION: 'CHEST_WITH_ACTION',
    ADVENT_CALENDAR: 'ADVENT_CALENDAR',
    TEASER: 'TEASER',
    FAB_MENU: 'FAB_MENU',
    ANNOUNCEMENT: 'ANNOUNCEMENT'
} as const;

export type PublicWidgetTypeEnum = typeof PublicWidgetTypeEnum[keyof typeof PublicWidgetTypeEnum];


