/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * Name
     * @type {string}
     * @memberof RegisterDto
     */
    'name': string;
    /**
     * Email
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Phone number starting with + followed by digits (12-16 characters: + and 11-15 digits)
     * @type {string}
     * @memberof RegisterDto
     */
    'phone': string;
}

