/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RequestEntity } from './request-entity';

/**
 * 
 * @export
 * @interface RequestsResponse
 */
export interface RequestsResponse {
    /**
     * 
     * @type {Array<RequestEntity>}
     * @memberof RequestsResponse
     */
    'requests': Array<RequestEntity>;
    /**
     * 
     * @type {number}
     * @memberof RequestsResponse
     */
    'total': number;
}

