/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RequestContact } from './request-contact';

/**
 * 
 * @export
 * @interface RequestEntity
 */
export interface RequestEntity {
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'projectId': string;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'widgetId': string;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'fullName'?: string;
    /**
     * 
     * @type {RequestContact}
     * @memberof RequestEntity
     */
    'contact': RequestContact;
    /**
     * 
     * @type {Array<string>}
     * @memberof RequestEntity
     */
    'prizes': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'status': RequestEntityStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RequestEntity
     */
    'device': RequestEntityDeviceEnum;
}

export const RequestEntityStatusEnum = {
    new: 'new',
    processed: 'processed',
    not_processed: 'not_processed',
    used: 'used'
} as const;

export type RequestEntityStatusEnum = typeof RequestEntityStatusEnum[keyof typeof RequestEntityStatusEnum];
export const RequestEntityDeviceEnum = {
    desktop: 'desktop',
    mobile_ios: 'mobile_ios',
    mobile_android: 'mobile_android'
} as const;

export type RequestEntityDeviceEnum = typeof RequestEntityDeviceEnum[keyof typeof RequestEntityDeviceEnum];


