/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * Token
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New Password
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}

