/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateWidgetDto
 */
export interface UpdateWidgetDto {
    /**
     * The ID of the project this widget belongs to
     * @type {string}
     * @memberof UpdateWidgetDto
     */
    'projectId'?: string;
    /**
     * The name of the widget
     * @type {string}
     * @memberof UpdateWidgetDto
     */
    'name'?: string;
    /**
     * The type of the widget
     * @type {string}
     * @memberof UpdateWidgetDto
     */
    'type'?: UpdateWidgetDtoTypeEnum;
    /**
     * Whether the widget is enabled
     * @type {boolean}
     * @memberof UpdateWidgetDto
     */
    'enabled'?: boolean;
    /**
     * JSON configuration for the widget
     * @type {object}
     * @memberof UpdateWidgetDto
     */
    'config'?: object;
}

export const UpdateWidgetDtoTypeEnum = {
    WHEEL_OF_FORTUNE: 'WHEEL_OF_FORTUNE',
    CONVEYOR_OF_GIFTS: 'CONVEYOR_OF_GIFTS',
    ACTION_TIMER: 'ACTION_TIMER',
    POSTCARD: 'POSTCARD',
    CHEST_WITH_ACTION: 'CHEST_WITH_ACTION',
    ADVENT_CALENDAR: 'ADVENT_CALENDAR',
    TEASER: 'TEASER',
    FAB_MENU: 'FAB_MENU',
    ANNOUNCEMENT: 'ANNOUNCEMENT'
} as const;

export type UpdateWidgetDtoTypeEnum = typeof UpdateWidgetDtoTypeEnum[keyof typeof UpdateWidgetDtoTypeEnum];


