/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateRequestDto
 */
export interface UpdateRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateRequestDto
     */
    'status': UpdateRequestDtoStatusEnum;
}

export const UpdateRequestDtoStatusEnum = {
    new: 'new',
    processed: 'processed',
    not_processed: 'not_processed',
    used: 'used'
} as const;

export type UpdateRequestDtoStatusEnum = typeof UpdateRequestDtoStatusEnum[keyof typeof UpdateRequestDtoStatusEnum];


