/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateProjectDto
 */
export interface UpdateProjectDto {
    /**
     * The title of the project
     * @type {string}
     * @memberof UpdateProjectDto
     */
    'title'?: string;
    /**
     * The website URL of the project
     * @type {string}
     * @memberof UpdateProjectDto
     */
    'websiteUrl'?: string;
    /**
     * Whether the project is enabled
     * @type {boolean}
     * @memberof UpdateProjectDto
     */
    'enabled'?: boolean;
}

