/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Widget } from './widget';

/**
 * 
 * @export
 * @interface UpdateProjectResponse
 */
export interface UpdateProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    'websiteUrl': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProjectResponse
     */
    'enabled': boolean;
    /**
     * 
     * @type {Array<Widget>}
     * @memberof UpdateProjectResponse
     */
    'widgets'?: Array<Widget>;
}

