/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Widget
 */
export interface Widget {
    /**
     * The unique identifier of the widget
     * @type {string}
     * @memberof Widget
     */
    'id': string;
    /**
     * The ID of the project this widget belongs to
     * @type {string}
     * @memberof Widget
     */
    'projectId': string;
    /**
     * The name of the widget
     * @type {string}
     * @memberof Widget
     */
    'name': string;
    /**
     * The type of the widget
     * @type {string}
     * @memberof Widget
     */
    'type': WidgetTypeEnum;
    /**
     * Whether the widget is enabled
     * @type {boolean}
     * @memberof Widget
     */
    'enabled': boolean;
    /**
     * JSON configuration for the widget
     * @type {object}
     * @memberof Widget
     */
    'config'?: object | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof Widget
     */
    'createdAt': string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof Widget
     */
    'updatedAt': string;
}

export const WidgetTypeEnum = {
    WHEEL: 'WHEEL',
    PIPELINE: 'PIPELINE',
    TIMER: 'TIMER',
    POSTCARD: 'POSTCARD'
} as const;

export type WidgetTypeEnum = typeof WidgetTypeEnum[keyof typeof WidgetTypeEnum];


