/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PublicWidget } from '../models';
/**
 * PublicWidgetsApi - axios parameter creator
 * @export
 */
export const PublicWidgetsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicWidgetControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('publicWidgetControllerFindOne', 'id', id)
            const localVarPath = `/api/public/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicWidgetControllerSpin: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('publicWidgetControllerSpin', 'id', id)
            const localVarPath = `/api/public/widgets/{id}/spin`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicWidgetsApi - functional programming interface
 * @export
 */
export const PublicWidgetsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicWidgetsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicWidgetControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicWidget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicWidgetControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicWidgetsApi.publicWidgetControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicWidgetControllerSpin(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicWidgetControllerSpin(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicWidgetsApi.publicWidgetControllerSpin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicWidgetsApi - factory interface
 * @export
 */
export const PublicWidgetsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicWidgetsApiFp(configuration)
    return {
        /**
         * 
         * @param {PublicWidgetsApiPublicWidgetControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicWidgetControllerFindOne(requestParameters: PublicWidgetsApiPublicWidgetControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<PublicWidget> {
            return localVarFp.publicWidgetControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PublicWidgetsApiPublicWidgetControllerSpinRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicWidgetControllerSpin(requestParameters: PublicWidgetsApiPublicWidgetControllerSpinRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.publicWidgetControllerSpin(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for publicWidgetControllerFindOne operation in PublicWidgetsApi.
 * @export
 * @interface PublicWidgetsApiPublicWidgetControllerFindOneRequest
 */
export interface PublicWidgetsApiPublicWidgetControllerFindOneRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicWidgetsApiPublicWidgetControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for publicWidgetControllerSpin operation in PublicWidgetsApi.
 * @export
 * @interface PublicWidgetsApiPublicWidgetControllerSpinRequest
 */
export interface PublicWidgetsApiPublicWidgetControllerSpinRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicWidgetsApiPublicWidgetControllerSpin
     */
    readonly id: string
}

/**
 * PublicWidgetsApi - object-oriented interface
 * @export
 * @class PublicWidgetsApi
 * @extends {BaseAPI}
 */
export class PublicWidgetsApi extends BaseAPI {
    /**
     * 
     * @param {PublicWidgetsApiPublicWidgetControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicWidgetsApi
     */
    public publicWidgetControllerFindOne(requestParameters: PublicWidgetsApiPublicWidgetControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return PublicWidgetsApiFp(this.configuration).publicWidgetControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PublicWidgetsApiPublicWidgetControllerSpinRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicWidgetsApi
     */
    public publicWidgetControllerSpin(requestParameters: PublicWidgetsApiPublicWidgetControllerSpinRequest, options?: RawAxiosRequestConfig) {
        return PublicWidgetsApiFp(this.configuration).publicWidgetControllerSpin(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

