/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreatePublicRequestDto } from '../models';
// @ts-ignore
import type { RequestEntity } from '../models';
/**
 * PublicRequestsApi - axios parameter creator
 * @export
 */
export const PublicRequestsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreatePublicRequestDto} createPublicRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicRequestControllerCreate: async (createPublicRequestDto: CreatePublicRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPublicRequestDto' is not null or undefined
            assertParamExists('publicRequestControllerCreate', 'createPublicRequestDto', createPublicRequestDto)
            const localVarPath = `/api/public/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPublicRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicRequestsApi - functional programming interface
 * @export
 */
export const PublicRequestsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicRequestsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreatePublicRequestDto} createPublicRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicRequestControllerCreate(createPublicRequestDto: CreatePublicRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequestEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicRequestControllerCreate(createPublicRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicRequestsApi.publicRequestControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicRequestsApi - factory interface
 * @export
 */
export const PublicRequestsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicRequestsApiFp(configuration)
    return {
        /**
         * 
         * @param {PublicRequestsApiPublicRequestControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicRequestControllerCreate(requestParameters: PublicRequestsApiPublicRequestControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RequestEntity> {
            return localVarFp.publicRequestControllerCreate(requestParameters.createPublicRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for publicRequestControllerCreate operation in PublicRequestsApi.
 * @export
 * @interface PublicRequestsApiPublicRequestControllerCreateRequest
 */
export interface PublicRequestsApiPublicRequestControllerCreateRequest {
    /**
     * 
     * @type {CreatePublicRequestDto}
     * @memberof PublicRequestsApiPublicRequestControllerCreate
     */
    readonly createPublicRequestDto: CreatePublicRequestDto
}

/**
 * PublicRequestsApi - object-oriented interface
 * @export
 * @class PublicRequestsApi
 * @extends {BaseAPI}
 */
export class PublicRequestsApi extends BaseAPI {
    /**
     * 
     * @param {PublicRequestsApiPublicRequestControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicRequestsApi
     */
    public publicRequestControllerCreate(requestParameters: PublicRequestsApiPublicRequestControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return PublicRequestsApiFp(this.configuration).publicRequestControllerCreate(requestParameters.createPublicRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

