/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeleteRequestResponse } from '../models';
// @ts-ignore
import type { RequestEntity } from '../models';
// @ts-ignore
import type { RequestsResponse } from '../models';
// @ts-ignore
import type { UpdateRequestDto } from '../models';
/**
 * RequestsApi - axios parameter creator
 * @export
 */
export const RequestsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [projectId] 
         * @param {RequestControllerFindAllPeriodEnum} [period] 
         * @param {RequestControllerFindAllStatusEnum} [status] 
         * @param {number} [skip] 
         * @param {number} [take] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerFindAll: async (projectId?: string, period?: RequestControllerFindAllPeriodEnum, status?: RequestControllerFindAllStatusEnum, skip?: number, take?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (projectId !== undefined) {
                localVarQueryParameter['projectId'] = projectId;
            }

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (take !== undefined) {
                localVarQueryParameter['take'] = take;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('requestControllerRemove', 'id', id)
            const localVarPath = `/api/requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateRequestDto} updateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerUpdate: async (id: string, updateRequestDto: UpdateRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('requestControllerUpdate', 'id', id)
            // verify required parameter 'updateRequestDto' is not null or undefined
            assertParamExists('requestControllerUpdate', 'updateRequestDto', updateRequestDto)
            const localVarPath = `/api/requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RequestsApi - functional programming interface
 * @export
 */
export const RequestsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RequestsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [projectId] 
         * @param {RequestControllerFindAllPeriodEnum} [period] 
         * @param {RequestControllerFindAllStatusEnum} [status] 
         * @param {number} [skip] 
         * @param {number} [take] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestControllerFindAll(projectId?: string, period?: RequestControllerFindAllPeriodEnum, status?: RequestControllerFindAllStatusEnum, skip?: number, take?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequestsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestControllerFindAll(projectId, period, status, skip, take, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RequestsApi.requestControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteRequestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RequestsApi.requestControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateRequestDto} updateRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestControllerUpdate(id: string, updateRequestDto: UpdateRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequestEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestControllerUpdate(id, updateRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RequestsApi.requestControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RequestsApi - factory interface
 * @export
 */
export const RequestsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RequestsApiFp(configuration)
    return {
        /**
         * 
         * @param {RequestsApiRequestControllerFindAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerFindAll(requestParameters: RequestsApiRequestControllerFindAllRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RequestsResponse> {
            return localVarFp.requestControllerFindAll(requestParameters.projectId, requestParameters.period, requestParameters.status, requestParameters.skip, requestParameters.take, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RequestsApiRequestControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerRemove(requestParameters: RequestsApiRequestControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteRequestResponse> {
            return localVarFp.requestControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RequestsApiRequestControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestControllerUpdate(requestParameters: RequestsApiRequestControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RequestEntity> {
            return localVarFp.requestControllerUpdate(requestParameters.id, requestParameters.updateRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for requestControllerFindAll operation in RequestsApi.
 * @export
 * @interface RequestsApiRequestControllerFindAllRequest
 */
export interface RequestsApiRequestControllerFindAllRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsApiRequestControllerFindAll
     */
    readonly projectId?: string

    /**
     * 
     * @type {'7d' | '30d' | '90d' | 'all'}
     * @memberof RequestsApiRequestControllerFindAll
     */
    readonly period?: RequestControllerFindAllPeriodEnum

    /**
     * 
     * @type {'new' | 'processed' | 'not_processed' | 'used'}
     * @memberof RequestsApiRequestControllerFindAll
     */
    readonly status?: RequestControllerFindAllStatusEnum

    /**
     * 
     * @type {number}
     * @memberof RequestsApiRequestControllerFindAll
     */
    readonly skip?: number

    /**
     * 
     * @type {number}
     * @memberof RequestsApiRequestControllerFindAll
     */
    readonly take?: number
}

/**
 * Request parameters for requestControllerRemove operation in RequestsApi.
 * @export
 * @interface RequestsApiRequestControllerRemoveRequest
 */
export interface RequestsApiRequestControllerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsApiRequestControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for requestControllerUpdate operation in RequestsApi.
 * @export
 * @interface RequestsApiRequestControllerUpdateRequest
 */
export interface RequestsApiRequestControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsApiRequestControllerUpdate
     */
    readonly id: string

    /**
     * 
     * @type {UpdateRequestDto}
     * @memberof RequestsApiRequestControllerUpdate
     */
    readonly updateRequestDto: UpdateRequestDto
}

/**
 * RequestsApi - object-oriented interface
 * @export
 * @class RequestsApi
 * @extends {BaseAPI}
 */
export class RequestsApi extends BaseAPI {
    /**
     * 
     * @param {RequestsApiRequestControllerFindAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsApi
     */
    public requestControllerFindAll(requestParameters: RequestsApiRequestControllerFindAllRequest = {}, options?: RawAxiosRequestConfig) {
        return RequestsApiFp(this.configuration).requestControllerFindAll(requestParameters.projectId, requestParameters.period, requestParameters.status, requestParameters.skip, requestParameters.take, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RequestsApiRequestControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsApi
     */
    public requestControllerRemove(requestParameters: RequestsApiRequestControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return RequestsApiFp(this.configuration).requestControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RequestsApiRequestControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestsApi
     */
    public requestControllerUpdate(requestParameters: RequestsApiRequestControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return RequestsApiFp(this.configuration).requestControllerUpdate(requestParameters.id, requestParameters.updateRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const RequestControllerFindAllPeriodEnum = {
    _7d: '7d',
    _30d: '30d',
    _90d: '90d',
    all: 'all'
} as const;
export type RequestControllerFindAllPeriodEnum = typeof RequestControllerFindAllPeriodEnum[keyof typeof RequestControllerFindAllPeriodEnum];
/**
 * @export
 */
export const RequestControllerFindAllStatusEnum = {
    new: 'new',
    processed: 'processed',
    not_processed: 'not_processed',
    used: 'used'
} as const;
export type RequestControllerFindAllStatusEnum = typeof RequestControllerFindAllStatusEnum[keyof typeof RequestControllerFindAllStatusEnum];
