/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from '../base';
/**
 * WidgetsApi - axios parameter creator
 * @export
 */
export const WidgetsApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @param {CreateWidgetDto} createWidgetDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerCreate: async (createWidgetDto, options = {}) => {
            // verify required parameter 'createWidgetDto' is not null or undefined
            assertParamExists('widgetControllerCreate', 'createWidgetDto', createWidgetDto);
            const localVarPath = `/api/widgets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(createWidgetDto, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} projectId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindAllByProject: async (projectId, options = {}) => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('widgetControllerFindAllByProject', 'projectId', projectId);
            const localVarPath = `/api/widgets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            if (projectId !== undefined) {
                localVarQueryParameter['projectId'] = projectId;
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindOne: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerFindOne', 'id', id);
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerRemove: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerRemove', 'id', id);
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerToggleEnabled: async (id, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerToggleEnabled', 'id', id);
            const localVarPath = `/api/widgets/{id}/toggle`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {string} id
         * @param {UpdateWidgetDto} updateWidgetDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerUpdate: async (id, updateWidgetDto, options = {}) => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerUpdate', 'id', id);
            // verify required parameter 'updateWidgetDto' is not null or undefined
            assertParamExists('widgetControllerUpdate', 'updateWidgetDto', updateWidgetDto);
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(updateWidgetDto, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * WidgetsApi - functional programming interface
 * @export
 */
export const WidgetsApiFp = function (configuration) {
    const localVarAxiosParamCreator = WidgetsApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @param {CreateWidgetDto} createWidgetDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerCreate(createWidgetDto, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerCreate(createWidgetDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @param {string} projectId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerFindAllByProject(projectId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerFindAllByProject(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerFindAllByProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerFindOne(id, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerRemove(id, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerToggleEnabled(id, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerToggleEnabled(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerToggleEnabled']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @param {string} id
         * @param {UpdateWidgetDto} updateWidgetDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerUpdate(id, updateWidgetDto, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerUpdate(id, updateWidgetDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    };
};
/**
 * WidgetsApi - factory interface
 * @export
 */
export const WidgetsApiFactory = function (configuration, basePath, axios) {
    const localVarFp = WidgetsApiFp(configuration);
    return {
        /**
         *
         * @param {WidgetsApiWidgetControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerCreate(requestParameters, options) {
            return localVarFp.widgetControllerCreate(requestParameters.createWidgetDto, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {WidgetsApiWidgetControllerFindAllByProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindAllByProject(requestParameters, options) {
            return localVarFp.widgetControllerFindAllByProject(requestParameters.projectId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {WidgetsApiWidgetControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindOne(requestParameters, options) {
            return localVarFp.widgetControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {WidgetsApiWidgetControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerRemove(requestParameters, options) {
            return localVarFp.widgetControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {WidgetsApiWidgetControllerToggleEnabledRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerToggleEnabled(requestParameters, options) {
            return localVarFp.widgetControllerToggleEnabled(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {WidgetsApiWidgetControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerUpdate(requestParameters, options) {
            return localVarFp.widgetControllerUpdate(requestParameters.id, requestParameters.updateWidgetDto, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * WidgetsApi - object-oriented interface
 * @export
 * @class WidgetsApi
 * @extends {BaseAPI}
 */
export class WidgetsApi extends BaseAPI {
    /**
     *
     * @param {WidgetsApiWidgetControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerCreate(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerCreate(requestParameters.createWidgetDto, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {WidgetsApiWidgetControllerFindAllByProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerFindAllByProject(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerFindAllByProject(requestParameters.projectId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {WidgetsApiWidgetControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerFindOne(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {WidgetsApiWidgetControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerRemove(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {WidgetsApiWidgetControllerToggleEnabledRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerToggleEnabled(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerToggleEnabled(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {WidgetsApiWidgetControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    widgetControllerUpdate(requestParameters, options) {
        return WidgetsApiFp(this.configuration).widgetControllerUpdate(requestParameters.id, requestParameters.updateWidgetDto, options).then((request) => request(this.axios, this.basePath));
    }
}
