/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateWidgetDto } from '../models';
// @ts-ignore
import type { UpdateWidgetDto } from '../models';
// @ts-ignore
import type { Widget } from '../models';
/**
 * WidgetsApi - axios parameter creator
 * @export
 */
export const WidgetsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateWidgetDto} createWidgetDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerCreate: async (createWidgetDto: CreateWidgetDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createWidgetDto' is not null or undefined
            assertParamExists('widgetControllerCreate', 'createWidgetDto', createWidgetDto)
            const localVarPath = `/api/widgets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWidgetDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindAllByProject: async (projectId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('widgetControllerFindAllByProject', 'projectId', projectId)
            const localVarPath = `/api/widgets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (projectId !== undefined) {
                localVarQueryParameter['projectId'] = projectId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerFindOne', 'id', id)
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerRemove', 'id', id)
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerToggleEnabled: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerToggleEnabled', 'id', id)
            const localVarPath = `/api/widgets/{id}/toggle`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateWidgetDto} updateWidgetDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerUpdate: async (id: string, updateWidgetDto: UpdateWidgetDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('widgetControllerUpdate', 'id', id)
            // verify required parameter 'updateWidgetDto' is not null or undefined
            assertParamExists('widgetControllerUpdate', 'updateWidgetDto', updateWidgetDto)
            const localVarPath = `/api/widgets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateWidgetDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WidgetsApi - functional programming interface
 * @export
 */
export const WidgetsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WidgetsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateWidgetDto} createWidgetDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerCreate(createWidgetDto: CreateWidgetDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Widget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerCreate(createWidgetDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerFindAllByProject(projectId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Widget>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerFindAllByProject(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerFindAllByProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Widget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Widget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerToggleEnabled(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Widget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerToggleEnabled(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerToggleEnabled']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateWidgetDto} updateWidgetDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async widgetControllerUpdate(id: string, updateWidgetDto: UpdateWidgetDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Widget>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.widgetControllerUpdate(id, updateWidgetDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WidgetsApi.widgetControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WidgetsApi - factory interface
 * @export
 */
export const WidgetsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WidgetsApiFp(configuration)
    return {
        /**
         * 
         * @param {WidgetsApiWidgetControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerCreate(requestParameters: WidgetsApiWidgetControllerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Widget> {
            return localVarFp.widgetControllerCreate(requestParameters.createWidgetDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WidgetsApiWidgetControllerFindAllByProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindAllByProject(requestParameters: WidgetsApiWidgetControllerFindAllByProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Widget>> {
            return localVarFp.widgetControllerFindAllByProject(requestParameters.projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WidgetsApiWidgetControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerFindOne(requestParameters: WidgetsApiWidgetControllerFindOneRequest, options?: RawAxiosRequestConfig): AxiosPromise<Widget> {
            return localVarFp.widgetControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WidgetsApiWidgetControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerRemove(requestParameters: WidgetsApiWidgetControllerRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<Widget> {
            return localVarFp.widgetControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WidgetsApiWidgetControllerToggleEnabledRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerToggleEnabled(requestParameters: WidgetsApiWidgetControllerToggleEnabledRequest, options?: RawAxiosRequestConfig): AxiosPromise<Widget> {
            return localVarFp.widgetControllerToggleEnabled(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {WidgetsApiWidgetControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        widgetControllerUpdate(requestParameters: WidgetsApiWidgetControllerUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<Widget> {
            return localVarFp.widgetControllerUpdate(requestParameters.id, requestParameters.updateWidgetDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for widgetControllerCreate operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerCreateRequest
 */
export interface WidgetsApiWidgetControllerCreateRequest {
    /**
     * 
     * @type {CreateWidgetDto}
     * @memberof WidgetsApiWidgetControllerCreate
     */
    readonly createWidgetDto: CreateWidgetDto
}

/**
 * Request parameters for widgetControllerFindAllByProject operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerFindAllByProjectRequest
 */
export interface WidgetsApiWidgetControllerFindAllByProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof WidgetsApiWidgetControllerFindAllByProject
     */
    readonly projectId: string
}

/**
 * Request parameters for widgetControllerFindOne operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerFindOneRequest
 */
export interface WidgetsApiWidgetControllerFindOneRequest {
    /**
     * 
     * @type {string}
     * @memberof WidgetsApiWidgetControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for widgetControllerRemove operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerRemoveRequest
 */
export interface WidgetsApiWidgetControllerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof WidgetsApiWidgetControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for widgetControllerToggleEnabled operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerToggleEnabledRequest
 */
export interface WidgetsApiWidgetControllerToggleEnabledRequest {
    /**
     * 
     * @type {string}
     * @memberof WidgetsApiWidgetControllerToggleEnabled
     */
    readonly id: string
}

/**
 * Request parameters for widgetControllerUpdate operation in WidgetsApi.
 * @export
 * @interface WidgetsApiWidgetControllerUpdateRequest
 */
export interface WidgetsApiWidgetControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof WidgetsApiWidgetControllerUpdate
     */
    readonly id: string

    /**
     * 
     * @type {UpdateWidgetDto}
     * @memberof WidgetsApiWidgetControllerUpdate
     */
    readonly updateWidgetDto: UpdateWidgetDto
}

/**
 * WidgetsApi - object-oriented interface
 * @export
 * @class WidgetsApi
 * @extends {BaseAPI}
 */
export class WidgetsApi extends BaseAPI {
    /**
     * 
     * @param {WidgetsApiWidgetControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerCreate(requestParameters: WidgetsApiWidgetControllerCreateRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerCreate(requestParameters.createWidgetDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WidgetsApiWidgetControllerFindAllByProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerFindAllByProject(requestParameters: WidgetsApiWidgetControllerFindAllByProjectRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerFindAllByProject(requestParameters.projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WidgetsApiWidgetControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerFindOne(requestParameters: WidgetsApiWidgetControllerFindOneRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WidgetsApiWidgetControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerRemove(requestParameters: WidgetsApiWidgetControllerRemoveRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WidgetsApiWidgetControllerToggleEnabledRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerToggleEnabled(requestParameters: WidgetsApiWidgetControllerToggleEnabledRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerToggleEnabled(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {WidgetsApiWidgetControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WidgetsApi
     */
    public widgetControllerUpdate(requestParameters: WidgetsApiWidgetControllerUpdateRequest, options?: RawAxiosRequestConfig) {
        return WidgetsApiFp(this.configuration).widgetControllerUpdate(requestParameters.id, requestParameters.updateWidgetDto, options).then((request) => request(this.axios, this.basePath));
    }
}

