FROM node:20.19.0-alpine

WORKDIR /collector

RUN npm install -g pnpm@10.21.0

EXPOSE 4000

CMD ["sh", "-c", "pnpm --filter collector... install --frozen-lockfile && pnpm --filter collector run start:dev"]
