# Development Dockerfile для NestJS сервера
FROM node:20.19.0-alpine

# Устанавливаем рабочую директорию
WORKDIR /server

# Устанавливаем pnpm глобально
RUN npm install -g pnpm@10.15.1

# Открываем порт
EXPOSE 3000

# Запускаем в режиме разработки
CMD ["sh", "-c", "pnpm install --frozen-lockfile && pnpm --filter ./projects/server exec prisma generate && pnpm --filter ./projects/server run start:dev"]
